name: venv_graph_tracking_kit_sch_ge_2021
channels:
  - anaconda
  - gurobi
dependencies:
  - python=3.8
  - numpy=1.19.2
  - pandas=1.2.2
  - scipy=1.6.1
  - scikit-learn=0.23.2
  - scikit-image=0.17.2
  - cvxopt=1.2.0
  - gurobi=9.0.3
  - pip=21.0.1
  - imagecodecs=2021.1.11

  - pip:
    - tifffile==2021.1.14
